name: Deploy UNCST

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          composer install --no-dev --prefer-dist --optimize-autoloader

      - name: Prepare Target Directory Permissions
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            sudo chown -R ${{ secrets.DO_USERNAME }}:www-data /var/www/hrmis.uncst.go.ug
            sudo chmod -R g+rwX /var/www/hrmis.uncst.go.ug

      - name: Upload files to DigitalOcean
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          key: ${{ secrets.DO_SSH_KEY }}
          source: "."
          target: "/var/www/hrmis.uncst.go.ug"

      - name: Run migrations, optimize, and restart Supervisor
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            cd /var/www/hrmis.uncst.go.ug
            php artisan migrate --force
            php artisan optimize:clear
            php artisan optimize
            supervisorctl reread
            supervisorctl update
            supervisorctl restart all

      - name: Set proper permissions for storage and cache
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            chgrp -R www-data /var/www/hrmis.uncst.go.ug/storage /var/www/hrmis.uncst.go.ug/bootstrap/cache
            chmod -R ug+rwx /var/www/hrmis.uncst.go.ug/storage /var/www/hrmis.uncst.go.ug/bootstrap/cache

      # set right permissions for images directory in public, make sure its readable and writable
      - name: Set proper permissions for public directory
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            chgrp -R www-data /var/www/hrmis.uncst.go.ug/public
